# Matrices

matrix is a 2 dimensional array where numbers, symbols or expressions are arranges into rows and columns. using the concept of lists, one can easily define a matrix in python.
<br>

we define 2 matrices A and B

In [1]:
A = [[1,2,3],[4,5,6],[7,8,9]]
B = [[9,8,7],[6,5,4],[3,2,1]]

print(A)
print(B)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[9, 8, 7], [6, 5, 4], [3, 2, 1]]


In [4]:
# from sympy import pprint

print(A + B)
print(2*B)

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [9, 8, 7], [6, 5, 4], [3, 2, 1]]
[[9, 8, 7], [6, 5, 4], [3, 2, 1], [9, 8, 7], [6, 5, 4], [3, 2, 1]]


In [10]:
A*B #multiplication of lists containing lists isnot possible

TypeError: can't multiply sequence by non-int of type 'list'

In [11]:
A**2 #** or pow() doesnot work for list of lists

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [12]:
A[0].append(10)

In [13]:
A

[[1, 2, 3, 10], [4, 5, 6], [7, 8, 9]]

the matrix A being defined as a list of lists, python supports adding of single element to rows or columns, which falsifies the very definition of a matrix

thorugh all the above command we can see that even though it is possible to define a matrix as a list of lists, matrix manipulation is not straight forward as desired

## Numpy package

numpy is a library consisting of multidimensional array objects and package of functions for processing those arrays. Numpy stands for Numerical Python. The following operations can be performed in numpy

- Mathematical and logical operations on arrays
- fourier tranforms and routines for shape manipulation
- operations related to linear algebra


In [2]:
import numpy as np

numpy provides matrix() and array() functions

In [15]:
A1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(A1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
M1 = np.matrix([[1,2,3],[4,5,6],[7,8,9]])

print(M1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


**the difference between array() and matrix() ?**

- array() provides n-dimensional array while matrix() is strictly 2-d
- the * and ** operator performs elementwise in array while in matrix they are used for multiplication and finding powers

common errrors

In [17]:
N = np.matrix([1,2,3],[4,5,6],[7,8,9])

TypeError: Field elements must be 2- or 3-tuples, got '4'

## Matrix manipulation

In [20]:
# shape function for order

M1.shape

(3, 3)

In [22]:
print(M1.shape[0]) #no of rows
print(M1.shape[1]) #no of columns

3
3


In [23]:
# size function for number of elements
M1.size

9

In [24]:
# function zeroes creates an array of zeroes
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

zeros provide an array of zeros and not a matrix

the zeroes and ones function gives float value by default
<br>
np.zeros((4,4),int)


In [28]:
np.zeros((4,4),int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [30]:
np.ones((4,4),dtype = int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

## Matrix operations

In [3]:
d = np.matrix([[1,2,3],[4,5,6],[7,8,9]])

e = np.matrix([[1,2,3],[4,5,6],[7,8,9]])

f = np.matrix([[1,2,3],[4,5,6],[7,8,9]])

In [33]:
d + e

matrix([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]])

In [35]:
np.add(d,e)

matrix([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]])

In [36]:
d - e

matrix([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [37]:
np.multiply(d,e)

matrix([[ 1,  4,  9],
        [16, 25, 36],
        [49, 64, 81]])

In [47]:
d.dot(f) # matrix multiplication

matrix([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [48]:
e/d

matrix([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [49]:
np.divide(e,d)

matrix([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

### Transpose of a matrix

In [4]:
d.transpose()

matrix([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [5]:
np.transpose(d)

matrix([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [6]:
d.T

matrix([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

### Upper and lower triangular matrix

In [7]:
ut = np.triu(d)
ut

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

In [8]:
lt = np.tril(d)
lt

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

## numpy.linalg

linear algebra module

- rank, determinant, trace, inverse etc of an array
- eigen values of matrices
- matrix and vector products
- solve linear equations

### determinant

In [9]:
det = np.linalg.det(d)
det

0.0

### inverse of matrix

In [11]:
x = np.matrix([[1,2],[4,9]])
x**-1

matrix([[ 9., -2.],
        [-4.,  1.]])

In [12]:
np.linalg.inv(x)

matrix([[ 9., -2.],
        [-4.,  1.]])

### eigen values

In [16]:
print(d)

np.linalg.eigvals(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([ 1.61168440e+01, -1.11684397e+00, -9.75918483e-16])

In [17]:
h = np.matrix([[1,0,0],[0,9,0],[0,0,8]])

np.linalg.eigvals(h)

array([1., 9., 8.])

# Identity matrix
verify the following properties by suitable examples
- symmetric transpose of identity matrix is itself
- identity matrix is nonsimgular
- inverse of identity matrix is itself
- eigenvalues are all 1's
- multiplying any matrix by the unit matrix , gives the marix itself
- We always get an identity after multiplying two inverse matrices

In [1]:
import numpy as np

In [6]:
i = np.matrix([[1,0,0],[0,1,0],[0,0,1]])

print("identity matrix =\n ",i)

trans = np.transpose(i)

print("transpose of  matrix =\n ",i)

de = np.linalg.det(i)

print("determinant :\n ", de)

inv = np.linalg.inv(i)

print("inverse = \n", inv)

eig = np.linalg.eigvals(i)

print("eigen values : ",eig)

a = np.matrix([[1,0,0],[0,5,0],[0,0,9]])

print("a = \n",a)

print("a*i = \n",a*i)

a_i = np.linalg.inv(a)


identity matrix =
  [[1 0 0]
 [0 1 0]
 [0 0 1]]
transpose of  matrix =
  [[1 0 0]
 [0 1 0]
 [0 0 1]]
determinant :
  1.0
inverse = 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
eigen values :  [1. 1. 1.]
a = 
 [[1 0 0]
 [0 5 0]
 [0 0 9]]
a*i = 
 [[1 0 0]
 [0 5 0]
 [0 0 9]]


# Diagonal Matrix


verify the properties :
- addition, multiplication of diagonal matrix gives a diagonal matrix again:
- symmetric transpose of matrix is itself
- determinant of diag(ai ) = a1*a2...
- identity matrix is nonsingular if diagonal entries are all on zero
- diag(ai..)^-1 = diaag(a1^-1,....an^-1)
- eigen values are diagonal entries

In [10]:
d1 = np.matrix([[1,0,0],[0,2,0],[0,0,3]])
d2 = np.matrix([[4,0,0],[0,5,0],[0,0,6]])
print("d1 = \n",d1)
print("d2 = \n",d2)

d = d1 + d2
c = d1 * d2

print("d1 + d2 = \n",d)
print("d1 * d2 = \n", c)

tra = np.transpose(d1)
print("transpose = \n",d1)

#find inverse and eigen values of the same



d1 = 
 [[1 0 0]
 [0 2 0]
 [0 0 3]]
d2 = 
 [[4 0 0]
 [0 5 0]
 [0 0 6]]
d1 + d2 = 
 [[5 0 0]
 [0 7 0]
 [0 0 9]]
d1 * d2 = 
 [[ 4  0  0]
 [ 0 10  0]
 [ 0  0 18]]
transpose = 
 [[1 0 0]
 [0 2 0]
 [0 0 3]]


# Upper triangular matrix
- adding returns utm
- multiplying results in utm
- transpose will be ltm
- inverse remains utm
- determinant od diag(a1...an)  = a1*a2*....an
- eigen values are diagonal entries

In [13]:
u1 = np.matrix([[1,4,5],[0,2,6],[0,0,3]])
u2 = np.matrix([[4,1,2],[0,5,3],[0,0,6]])

print("u1 = \n",u1)
print("u2 = \n",u2)
 
u = u1 + u2
c = u1 * u2
 
print("u1 + u2 = \n",u)
print("u1 * u2 = \n", c)
 
tra = np.transpose(u1)
print("transpose = \n",u1)

de = np.linalg.det(u1)

print("determinant =\n",de)





u1 = 
 [[1 4 5]
 [0 2 6]
 [0 0 3]]
u2 = 
 [[4 1 2]
 [0 5 3]
 [0 0 6]]
u1 + u2 = 
 [[5 5 7]
 [0 7 9]
 [0 0 9]]
u1 * u2 = 
 [[ 4 21 44]
 [ 0 10 42]
 [ 0  0 18]]
transpose = 
 [[1 4 5]
 [0 2 6]
 [0 0 3]]
determinant =
 6.0


# Singular Matrix
- det is 0
- a non-invertible matrix is reffered to as singlular matrix, i.e, when the determinant of a matrix is zero, we cannot find its inverse, there will be multiplicative inverse for the matrix
- Product of singular and non singular matri gives singular matrix
   

In [8]:
import numpy as np

s = np.matrix([[1,4,7],[1,4,7],[2,3,0]])


print("singular =\n",s)

trans = np.transpose(s)

print("transpose of  matrix =\n",trans)

de = np.linalg.det(s)

print("determinant :\n", de)

# inv = np.linalg.inv(s)

# print("inverse = \n", inv)

eig = np.linalg.eigvals(s)

print("eigen values : ",eig)

a = np.matrix([[1,0,0],[0,5,0],[0,0,9]])
print("a = \n",a)

print("a*s =\n",a*s)
d = np.linalg.det(a*s)
print("determinant of a*s = ",d)



singular =
 [[1 4 7]
 [1 4 7]
 [2 3 0]]
transpose of  matrix =
 [[1 1 2]
 [4 4 3]
 [7 7 0]]
determinant :
 0.0
eigen values :  [ 8.92261629e+00 -4.81385765e-17 -3.92261629e+00]
a = 
 [[1 0 0]
 [0 5 0]
 [0 0 9]]
a*s =
 [[ 1  4  7]
 [ 5 20 35]
 [18 27  0]]
determinant of a*s =  0.0


# Rank of a Matrix

In [9]:
from numpy.linalg import matrix_rank

i = np.eye(4)

print(i)

r = matrix_rank(i)

print("rank = ",r)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
rank =  4


In [18]:
i = np.eye(4)
i[3,3] = 0

print(i)
r = matrix_rank(i)

print("rank = ",r)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]]
rank =  3


In [20]:
p = np.matrix([[1,1,-1],[2,-3,4],[3,-2,3]])
q = np.matrix([[-1,-2,-1],[6,12,6],[5,10,5]])

print(p+q)
r = matrix_rank(p+q)

print("rank = ",r)


[[ 0 -1 -2]
 [ 8  9 10]
 [ 8  8  8]]
rank =  2


In [21]:
from numpy.linalg import matrix_rank

i = np.ones((4,4))

print(i)
r = matrix_rank(i)

print("rank = ",r)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
rank =  1


In [24]:
b = np.matrix([[2,-1,3],[1,0,1],[1,1,4]])
print(b)
r = matrix_rank(b)

print("rank = ",r)
print()
bt = np.transpose(b)

print(bt)
r = matrix_rank(bt)

print("rank = ",r)


[[ 2 -1  3]
 [ 1  0  1]
 [ 1  1  4]]
rank =  3

[[ 2  1  1]
 [-1  0  1]
 [ 3  1  4]]
rank =  3


In [26]:
#show rank of p is no of non zero eigen values
p = np.matrix([[1,1,-1],[2,-3,4],[3,-2,3]])

print(p)
r = matrix_rank(p)

print("rank = ",r)


eig = np.linalg.eigvals(p)

print("eigen values : ",eig)



[[ 1  1 -1]
 [ 2 -3  4]
 [ 3 -2  3]]
rank =  2
eigen values :  [ 1.00000000e+00+0.00000000e+00j -2.24492778e-16+4.40332636e-08j
 -2.24492778e-16-4.40332636e-08j]


# system of linear equations

a linear equation in variables x1,x2,..xn is an equation of the form a1x1, a2x2,...an,xn and $b$ are constants.

the constants ai is called the coefficient of xi

A system of linear equations is a finite collection of linear equations in the same variables.

linear wquations in $n$ variables $x_1, x_2. \ldots. x_n$ <br>

$a_{11}x_1 + a_{12}x_2 + \ldots + a_{1n}x_n = b_1$ <br>

$a_{21}x_1 + a_{22}x_2 + \ldots + a_{2n}x_n = b_2$ <br>

$\ldots$ <br>

$a_{m1}x_1 + a_{m2}x_2 + \ldots + a_{mn}x_n = b_m$ <br>

 A solution of a linear system is an assignment of values to the variables $x_1, x_2 \ldots, x_n$ such that each of the equations is satisfied. The set of all solutions of a linear system is called the solution set of the system

in a matrix notation a linear system is $AX = B$, where <br>

$A = \begin{bmatrix}
a_{11} & a_{12} & \ldots & a_{1n} \\ 
a_{11} & a_{12} & \ldots & a_{1n} \\ 
    & \ldots & \\
a_{m1} & a_{m2} & \ldots & a_{mn} \\ 
\end{bmatrix} $ is the coefficient matrix , <br>

$X = \begin{bmatrix}
x_1 \\
x_2 \\
\vdots \\
x_n \\
\end{bmatrix} $ and
$B = \begin{bmatrix}
xb1 \\
b_2 \\
\vdots \\
b_n \\
\end{bmatrix} $.


python has numpy.linalg.solve() to solve these sytem of linear equations

syntax

numpy.linalg.solve(A,B)


Q. Find all solutions for the linear system <br>

$x_1 + 2x_2 - x_3 = 1$ <br>
$2x_1 + x_2 + 4x_3 = 2$ <br>
$3x_1 + 3x_2 + 4x_3 = 1$


In [4]:
import numpy as np
A = np.array([[1,2,-1],[2,1,4],[3,3,4]])
B = np.array([1,2,1])

print(np.linalg.solve(A,B))



[ 7. -4. -2.]


In [5]:
A = np.matrix([[1,2,-1],[2,1,4],[3,3,4]])
B = np.matrix([1,2,1])

print(np.linalg.solve(A,B))

ValueError: solve: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (m,m),(m,n)->(m,n) (size 1 is different from 3)

this is because $B$ is a $m \times 1$ matrix in the matrix equivalent of linear system of equations

In [8]:
A = np.matrix([[1,2,-1],[2,1,4],[3,3,4]])
B = np.matrix([[1],[2],[1]])

print(np.linalg.solve(A,B))

[[ 7.]
 [-4.]
 [-2.]]


 The function np.linalg.solve() works only if A is a non-singular matrix

In [10]:
A = np.matrix([[1,-1,1,-1],[1,-1,1,1],[4,-4,4,0],[-2,2,-2,1]])
B = np.matrix([[2],[0],[4],[-3]])

print(np.linalg.solve(A,B))

LinAlgError: Singular matrix

this is because determinant of A is 0

linalg.solve() only works oif the matrix is a square matrix

In [12]:
A = np.matrix([[1,-1,1,-1],[1,-1,1,1],[4,-4,4,0]])
B = np.matrix([[2],[0],[4]])

print(np.linalg.solve(A,B))

LinAlgError: Last 2 dimensions of the array must be square

## Exercise problems

### questions

1.  write a program to solve any system of linear equations(user input), check whether the coefficient matrix is singular or not. If singular , print no solution. If non singular then print the inverse exst and solve the system of equation

In [ ]:
l = []
m = []
n = []
p = []



import numpy as np
A = np.array([[1,3,-5],[4,2,1]])
B = np.array([1,2])
if  (A.shape[0] == A.shape[1]):
    de = np.linalg.det(A)
    if de ==0:
        print("determinant :\n", de)
        print("therefore no solution")
    else:
        print(np.linalg.solve(A,B))

        # using inverse method X = A^-1 * B

        x =np.linalg.inv(A).dot(B)
        print("uding inverse method = " ,x)
else:
    print("no solution- not square matrix")

2. solve the following system of linear equations 
    - $x_1 + 2x_2 - x_3 = -1$
    - $2x_1 + x_2 + 4x_3 = 2$
    - $3x_1 + 3x_2 + 4x_3 = 1$

In [23]:
import numpy as np
A = np.array([[1,2,-1],[2,1,4],[3,3,4]])
B = np.array([-1,2,1])
de = np.linalg.det(A)
if de ==0:

    print("determinant :\n", de)
    print("therefore no solution")
else:
    print(np.linalg.solve(A,B))

[ 1.66666667e+00 -1.33333333e+00 -2.22044605e-16]


In [22]:
# using inverse method X = A^-1 * B

x =np.linalg.inv(A).dot(B)
x

array([ 1.66666667, -1.33333333,  0.        ])

3. solve
    - $x_1 - x_2 + x_3 - x_4 = 2$
    - $x_1 - x_2 + x_3 + x_4 = 0$
    - $4x_1 - 4x_2 + 4x_3 = 4$
    - $-2x_1 + 2x_2 - 2x_3 + x_4 = -3$

In [5]:
A = np.matrix([[1,-1,1,-1],[1,-1,1,1],[4,-4,4,0],[-2,2,-2,1]])
B = np.matrix([[2],[0],[4],[-3]])
de = np.linalg.det(A)

if de ==0:

    print("determinant :\n", de)
    print("therefore no solution")
else:
    print(np.linalg.solve(A,B))

determinant :
 0.0
therefore no solution


4. solve
    - $x_1 - 2x_2 - x_3 = 1$
    - $2x_1 + x_2 - 5x_3 = 2$
    - $3x_1 + 3x_2 + 4x_3 = 1$

In [27]:
import numpy as np
A = np.array([[1,-2,-1],[2,1,-5],[3,3,4]])
B = np.array([1,2,1])
de = np.linalg.det(A)
if de ==0:

    print("determinant :\n", de)
    print("therefore no solution")
else:
    print(np.linalg.solve(A,B))

# using inverse method X = A^-1 * B

x =np.linalg.inv(A).dot(B)
print("uding inverse method = " ,x)

[ 0.64516129 -0.09677419 -0.16129032]
uding inverse method =  [ 0.64516129 -0.09677419 -0.16129032]


5. solve
    - $x_1 + 2x_2 + x_3 = 4$
    - $4x_1 + 5x_2 + 6x_3 = 7$
    - $7x_1 + 8x_2 + 9x_3 = 10$

In [28]:
import numpy as np
A = np.array([[1,2,-1],[4,5,6],[7,8,9]])
B = np.array([4,7,10])
de = np.linalg.det(A)
if de ==0:

    print("determinant :\n", de)
    print("therefore no solution")
else:
    print(np.linalg.solve(A,B))

# using inverse method X = A^-1 * B

x =np.linalg.inv(A).dot(B)
print("uding inverse method = " ,x)

[-2.00000000e+00  3.00000000e+00 -1.74463618e-16]
uding inverse method =  [-2.00000000e+00  3.00000000e+00 -3.88578059e-16]


5. solve
    - $x_1 + 3x_2 - 5x_3 = 1$
    - $4x_1 + 2x_2 + x_3 = 2$

In [38]:
import numpy as np
A = np.array([[1,3,-5],[4,2,1]])
B = np.array([1,2])
if  (A.shape[0] == A.shape[1]):
    de = np.linalg.det(A)
    if de ==0:
        print("determinant :\n", de)
        print("therefore no solution")
    else:
        print(np.linalg.solve(A,B))

        # using inverse method X = A^-1 * B

        x =np.linalg.inv(A).dot(B)
        print("uding inverse method = " ,x)
else:
    print("no solution- not square matrix")

no solution- not square matrix


6. suppose a fruit seller sold 20 mangoes + 10 oranges in one day for 350 dollars. next day 17 mangoes + 22 oranges for 500 dollars. find the prices of one mango and one orange

In [1]:
import numpy as np
A = np.array([[20,10],[17,22]])
B = np.array([350,500])
de = np.linalg.det(A)
if de ==0:

    print("determinant :\n", de)
    print("therefore no solution")
else:
    print(np.linalg.solve(A,B))

# using inverse method X = A^-1 * B

x =np.linalg.inv(A).dot(B)
print("uding inverse method = " ,x)

[10. 15.]
uding inverse method =  [10. 15.]


# Solving non Linear equations 

The solution to  non linear equations is through matrix operations while for nonlinear they require solvers such as scipy optimize and fsolve to numerically find the solution
Q1. **Solve the equation** $f(x) = x^{2}-5$



Solving a non linear eq involves first putting it inthe  form of f(x)=0


We know the function f and we want to find the valur of x that gives f(x)=0


To solve this 
- define the function f(x)
- set an initial guess for x.
- we need to import a library:from scipy.optimize import fsolve
- call the func fsolve: x=fsolve(f,x0)
- f is the name of the function ur solving and x0 is ur initial guess




## Funtion in single variables

In [14]:
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

from scipy.optimize import fsolve

In [9]:
from re import X


def f(x):
    return x**2 - 5

x = fsolve(f,2)

print(x,f(x))


[2.23606798] [-1.77635684e-15]


## function in muliple variables

Q2. **solve the function** $x^{2} + y^{2} = 16

In [21]:
def myf(z):
    x = z[0]
    y = z[1]

    F = np.empty((2))
    F[0] = x**2 + y**2 - 16
    return F

zguess = np.array([1,1])

z = fsolve(myf,zguess)

print(z,myf(z))

[1. 1.] [-14.   1.]


## Exercises
### solve single equations with one variable

1. $x^{2} + x + 1 = 3$
2. $y + 2*Cos(y) = 0$ 

In [4]:
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

from scipy.optimize import fsolve
from re import X


def f(x):
    return x**2 - x - 2

x = fsolve(f,2)

print(x,f(x))


[2.] [0.]


In [25]:
import math
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

from scipy.optimize import fsolve
from re import X


def f(y):
    return y - 2*math.cos(y) 

y = fsolve(f,2)

print(y,f(y))


[1.02986653] [0.]


# Sequence
what is a sequence?

A sequence is the generic term for an ordered set

In [1]:
from sympy import SeqFormula, Symbol

n = Symbol('n')
s = SeqFormula(n**2, (n,0,5))
s.formula



n**2

In [8]:

#for value at a perticular
s.coeff(3)


9

**supports slicing**

In [3]:
s[:]

[0, 1, 4, 9, 16, 25]

In [4]:
s[1:4]

[1, 4, 9]

**Sequence elements are displayed using list() command**

In [5]:
list(s)

[0, 1, 4, 9, 16, 25]

## lets discuss on few types of sequence in python

- strings : a group of characters
  
  
  to declare an empty string we may use the function str()

In [6]:
name = str()

name

''

In [7]:
name = str('ann')
name

'ann'

- list: is an ordered group of items. to declare it, we use the square brackets.

In [9]:
groceries = ['milk','bread','eggs']
groceries

['milk', 'bread', 'eggs']

In [10]:
# a list can hold all kind of items
mylist = [1,'2',3.0,False]
mylist

[1, '2', 3.0, False]

In [ ]:
#also, a list is mutable. This means we can change a value.
mylist[0] = 0

- tuples:a tuple is immutable group of items

In [12]:
n = (1,2)
n

(1, 2)

- range

In [2]:
# range(start, stop,step)

for i in range(0, 10, 2):
    print(i)


0
2
4
6
8


In [4]:
# program to generate sequence 3,5,7,9....19

for i in range(1, 20, 2):
    print(i)


1
3
5
7
9
11
13
15
17
19


# Sequence operations

## concatenation

In [5]:
[1, 2, 3] + [1, 2, 3]

[1, 2, 3, 1, 2, 3]

In [6]:

(1,2,3) + (2)

TypeError: can only concatenate tuple (not "int") to tuple

In [8]:
(9,0,7)+(9,)

(9, 0, 7, 9)

## repeat

In [9]:
(1,2,3) *3

(1, 2, 3, 1, 2, 3, 1, 2, 3)

In [10]:
[1,2,3]*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [11]:
"b"*3

'bbb'

## membership

In [12]:
'da' in 'daisy'

True

In [13]:
'z' in [1,2,3,'z']

True

In [14]:
1 in range(1,3)

True

# sequence functions

## len

In [15]:
d = 'bla'

len(d)

3

In [16]:
d = [1,2,234,2,234,23,33]
len(d)

7

## max or min

In [17]:
print(max([12,3,45,1]))

45


## index

In [18]:
"joel".index('o')

1

## count

In [21]:
"deeeeeez plolp".count("e")

6