## Matrices

matrix is a 2 dimensional array where numbers, symbols or expressions are arranges into rows and columns. using the concept of lists, one can easily define a matrix in python.
<br>

we define 2 matrices A and B

In [1]:
A = [[1,2,3],[4,5,6],[7,8,9]]
B = [[9,8,7],[6,5,4],[3,2,1]]

print(A)
print(B)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[9, 8, 7], [6, 5, 4], [3, 2, 1]]


In [4]:
# from sympy import pprint

print(A + B)
print(2*B)

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [9, 8, 7], [6, 5, 4], [3, 2, 1]]
[[9, 8, 7], [6, 5, 4], [3, 2, 1], [9, 8, 7], [6, 5, 4], [3, 2, 1]]


In [10]:
A*B #multiplication of lists containing lists isnot possible

TypeError: can't multiply sequence by non-int of type 'list'

In [11]:
A**2 #** or pow() doesnot work for list of lists

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [12]:
A[0].append(10)

In [13]:
A

[[1, 2, 3, 10], [4, 5, 6], [7, 8, 9]]

the matrix A being defined as a list of lists, python supports adding of single element to rows or columns, which falsifies the very definition of a matrix

thorugh all the above command we can see that even though it is possible to define a matrix as a list of lists, matrix manipulation is not straight forward as desired

## Numpy package

numpy is a library consisting of multidimensional array objects and package of functions for processing those arrays. Numpy stands for Numerical Python. The following operations can be performed in numpy

- Mathematical and logical operations on arrays
- fourier tranforms and routines for shape manipulation
- operations related to linear algebra


In [14]:
import numpy as np

numpy provides matrix() and array() functions

In [15]:
A1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(A1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
M1 = np.matrix([[1,2,3],[4,5,6],[7,8,9]])

print(M1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


**the difference between array() and matrix() ?**

- array() provides n-dimensional array while matrix() is strictly 2-d
- the * and ** operator performs elementwise in array while in matrix they are used for multiplication and finding powers

common errrors

In [17]:
N = np.matrix([1,2,3],[4,5,6],[7,8,9])

TypeError: Field elements must be 2- or 3-tuples, got '4'

## Matrix manipulation

In [20]:
# shape function for order

M1.shape

(3, 3)

In [22]:
print(M1.shape[0]) #no of rows
print(M1.shape[1]) #no of columns

3
3


In [23]:
# size function for number of elements
M1.size

9

In [24]:
# function zeroes creates an array of zeroes
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

zeros provide an array of zeros and not a matrix

the zeroes and ones function gives float value by default
<br>
np.zeros((4,4),int)


In [28]:
np.zeros((4,4),int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [30]:
np.ones((4,4),dtype = int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

## Matrix operations

In [32]:
d = np.matrix([[1,2,3],[4,5,6],[7,8,9]])

e = np.matrix([[1,2,3],[4,5,6],[7,8,9]])

f = np.matrix([[1,2,3],[4,5,6],[7,8,9]])

In [33]:
d + e

matrix([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]])

In [35]:
np.add(d,e)

matrix([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]])

In [36]:
d - e

matrix([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [37]:
np.multiply(d,e)

matrix([[ 1,  4,  9],
        [16, 25, 36],
        [49, 64, 81]])

In [47]:
d.dot(f) # matrix multiplication

matrix([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [48]:
e/d

matrix([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [49]:
np.divide(e,d)

matrix([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])