# Rank of a Matrix

In [9]:
from numpy.linalg import matrix_rank

i = np.eye(4)

print(i)

r = matrix_rank(i)

print("rank = ",r)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
rank =  4


In [18]:
i = np.eye(4)
i[3,3] = 0

print(i)
r = matrix_rank(i)

print("rank = ",r)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]]
rank =  3


In [21]:
from numpy.linalg import matrix_rank

i = np.ones((4,4))

print(i)
r = matrix_rank(i)

print("rank = ",r)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
rank =  1


In [20]:
p = np.matrix([[1,1,-1],[2,-3,4],[3,-2,3]])
q = np.matrix([[-1,-2,-1],[6,12,6],[5,10,5]])

print(p+q)
r = matrix_rank(p+q)

print("rank = ",r)


[[ 0 -1 -2]
 [ 8  9 10]
 [ 8  8  8]]
rank =  2


In [24]:
b = np.matrix([[2,-1,3],[1,0,1],[1,1,4]])
print(b)
r = matrix_rank(b)

print("rank = ",r)
print()
bt = np.transpose(b)

print(bt)
r = matrix_rank(bt)

print("rank = ",r)


[[ 2 -1  3]
 [ 1  0  1]
 [ 1  1  4]]
rank =  3

[[ 2  1  1]
 [-1  0  1]
 [ 3  1  4]]
rank =  3


In [26]:
#show rank of p is no of non zero eigen values
p = np.matrix([[1,1,-1],[2,-3,4],[3,-2,3]])

print(p)
r = matrix_rank(p)

print("rank = ",r)


eig = np.linalg.eigvals(p)

print("eigen values : ",eig)



[[ 1  1 -1]
 [ 2 -3  4]
 [ 3 -2  3]]
rank =  2
eigen values :  [ 1.00000000e+00+0.00000000e+00j -2.24492778e-16+4.40332636e-08j
 -2.24492778e-16-4.40332636e-08j]
