# system of linear equations


a linear equation in variables x1,x2,..xn is an equation of the form a1x1, a2x2,...an,xn and $b$ are constants.

the constants ai is called the coefficient of xi


A system of linear equations is a finite collection of linear equations in the same variables.

linear wquations in $n$ variables $x_1, x_2. \ldots. x_n$ <br>

$a_{11}x_1 + a_{12}x_2 + \ldots + a_{1n}x_n = b_1$ <br>

$a_{21}x_1 + a_{22}x_2 + \ldots + a_{2n}x_n = b_2$ <br>

$\ldots$ <br>

$a_{m1}x_1 + a_{m2}x_2 + \ldots + a_{mn}x_n = b_m$ <br>


A solution of a linear system is an assignment of values to the variables $x_1, x_2 \ldots, x_n$ such that each of the equations is satisfied. The set of all solutions of a linear system is called the solution set of the system


in a matrix notation a linear system is $AX = B$, where <br>

$A = \begin{bmatrix}
a*{11} & a*{12} & \ldots & a*{1n} \\
a*{11} & a*{12} & \ldots & a*{1n} \\
& \ldots & \\
a*{m1} & a*{m2} & \ldots & a\_{mn} \\
\end{bmatrix} $ is the coefficient matrix , <br>

$X = \begin{bmatrix}
x_1 \\
x_2 \\
\vdots \\
x_n \\
\end{bmatrix} $ and
$B = \begin{bmatrix}
xb1 \\
b_2 \\
\vdots \\
b_n \\
\end{bmatrix} $.


python has numpy.linalg.solve() to solve these sytem of linear equations

syntax

numpy.linalg.solve(A,B)


Q. Find all solutions for the linear system <br>

$x_1 + 2x_2 - x_3 = 1$ <br>
$2x_1 + x_2 + 4x_3 = 2$ <br>
$3x_1 + 3x_2 + 4x_3 = 1$


In [4]:
import numpy as np
A = np.array([[1, 2, -1], [2, 1, 4], [3, 3, 4]])
B = np.array([1, 2, 1])

print(np.linalg.solve(A, B))


[ 7. -4. -2.]


In [8]:
C = np.matrix([[1, 2, -1], [2, 1, 4], [3, 3, 4]])
B = np.matrix([1, 2, 1])

print(np.linalg.solve(C, B))


ValueError: solve: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (m,m),(m,n)->(m,n) (size 1 is different from 3)

this is because $B$ is a $m \times 1$ matrix in the matrix equivalent of linear system of equations


In [8]:
A = np.matrix([[1, 2, -1], [2, 1, 4], [3, 3, 4]])
B = np.matrix([[1], [2], [1]])

print(np.linalg.solve(A, B))


[[ 7.]
 [-4.]
 [-2.]]


The function np.linalg.solve() works only if A is a non-singular matrix


In [1]:
A = np.matrix([[1, -1, 1, -1], [1, -1, 1, 1], [4, -4, 4, 0], [-2, 2, -2, 1]])
B = np.matrix([[2], [0], [4], [-3]])

print(np.linalg.solve(A, B))


NameError: name 'np' is not defined

this is because determinant of A is 0


linalg.solve() only works oif the matrix is a square matrix


In [12]:
A = np.matrix([[1, -1, 1, -1], [1, -1, 1, 1], [4, -4, 4, 0]])
B = np.matrix([[2], [0], [4]])

print(np.linalg.solve(A, B))


LinAlgError: Last 2 dimensions of the array must be square

## Exercise problems


### questions


1.  write a program to solve any system of linear equations(user input), check whether the coefficient matrix is singular or not. If singular , print no solution. If non singular then print the inverse exst and solve the system of equation


In [1]:
import numpy as np
l = [int(x)
     for x in input("Enter coeefficirnts of  first equation : ").split()]
m = [int(x)
     for x in input("Enter coeefficirnts of  second equation : ").split()]
n = [int(x)
     for x in input("Enter coeefficirnts of  third equation : ").split()]

p = [int(x) for x in input("Enter the three constants in order: ").split()]


A = np.array([l, m, n])
B = np.array(p)
if (A.shape[0] == A.shape[1]):
    de = np.linalg.det(A)
    if de == 0:
        print("determinant :\n", de)
        print("therefore no solution")
    else:
        print(np.linalg.solve(A, B))

        # using inverse method X = A^-1 * B

        x = np.linalg.inv(A).dot(B)
        print("uding inverse method = ", x)
else:
    print("no solution- not square matrix")


Enter coeefficirnts of  first equation : 1 2 -1
Enter coeefficirnts of  second equation : 2 1 4
Enter coeefficirnts of  third equation : 3 3 4
Enter the three constants in order: -1 2 1
[ 1.66666667e+00 -1.33333333e+00 -2.22044605e-16]
uding inverse method =  [ 1.66666667 -1.33333333  0.        ]


2. solve the following system of linear equations
   - $x_1 + 2x_2 - x_3 = -1$
   - $2x_1 + x_2 + 4x_3 = 2$
   - $3x_1 + 3x_2 + 4x_3 = 1$


In [23]:
import numpy as np
A = np.array([[1, 2, -1], [2, 1, 4], [3, 3, 4]])
B = np.array([-1, 2, 1])
de = np.linalg.det(A)
if de == 0:

    print("determinant :\n", de)
    print("therefore no solution")
else:
    print(np.linalg.solve(A, B))


[ 1.66666667e+00 -1.33333333e+00 -2.22044605e-16]


In [22]:
# using inverse method X = A^-1 * B

x = np.linalg.inv(A).dot(B)
x


array([ 1.66666667, -1.33333333,  0.        ])

3. solve
   - $x_1 - x_2 + x_3 - x_4 = 2$
   - $x_1 - x_2 + x_3 + x_4 = 0$
   - $4x_1 - 4x_2 + 4x_3 = 4$
   - $-2x_1 + 2x_2 - 2x_3 + x_4 = -3$


In [5]:
A = np.matrix([[1, -1, 1, -1], [1, -1, 1, 1], [4, -4, 4, 0], [-2, 2, -2, 1]])
B = np.matrix([[2], [0], [4], [-3]])
de = np.linalg.det(A)

if de == 0:

    print("determinant :\n", de)
    print("therefore no solution")
else:
    print(np.linalg.solve(A, B))


determinant :
 0.0
therefore no solution


4. solve
   - $x_1 - 2x_2 - x_3 = 1$
   - $2x_1 + x_2 - 5x_3 = 2$
   - $3x_1 + 3x_2 + 4x_3 = 1$


In [2]:
import numpy as np
A = np.array([[1, -2, -1], [2, 1, -5], [3, 3, 4]])
B = np.array([1, 2, 1])
de = np.linalg.det(A)
if de == 0:

    print("determinant :\n", de)
    print("therefore no solution")
else:
    print(np.linalg.solve(A, B))


x = np.linalg.inv(A).dot(B)
print("uding inverse method = ", x)


[ 0.64516129 -0.09677419 -0.16129032]
uding inverse method =  [ 0.64516129 -0.09677419 -0.16129032]


5. solve
   - $x_1 + 2x_2 + x_3 = 4$
   - $4x_1 + 5x_2 + 6x_3 = 7$
   - $7x_1 + 8x_2 + 9x_3 = 10$


In [28]:
import numpy as np
A = np.array([[1, 2, -1], [4, 5, 6], [7, 8, 9]])
B = np.array([4, 7, 10])
de = np.linalg.det(A)
if de == 0:

    print("determinant :\n", de)
    print("therefore no solution")
else:
    print(np.linalg.solve(A, B))

# using inverse method X = A^-1 * B

x = np.linalg.inv(A).dot(B)
print("uding inverse method = ", x)


[-2.00000000e+00  3.00000000e+00 -1.74463618e-16]
uding inverse method =  [-2.00000000e+00  3.00000000e+00 -3.88578059e-16]


5. solve
   - $x_1 + 3x_2 - 5x_3 = 1$
   - $4x_1 + 2x_2 + x_3 = 2$


In [38]:
import numpy as np
A = np.array([[1, 3, -5], [4, 2, 1]])
B = np.array([1, 2])
if (A.shape[0] == A.shape[1]):
    de = np.linalg.det(A)
    if de == 0:
        print("determinant :\n", de)
        print("therefore no solution")
    else:
        print(np.linalg.solve(A, B))

        # using inverse method X = A^-1 * B

        x = np.linalg.inv(A).dot(B)
        print("uding inverse method = ", x)
else:
    print("no solution- not square matrix")


no solution- not square matrix


6. suppose a fruit seller sold 20 mangoes + 10 oranges in one day for 350 dollars. next day 17 mangoes + 22 oranges for 500 dollars. find the prices of one mango and one orange


In [29]:
import numpy as np
A = np.array([[20, 10], [17, 22]])
B = np.array([350, 500])
de = np.linalg.det(A)
if de == 0:

    print("determinant :\n", de)
    print("therefore no solution")
else:
    print(np.linalg.solve(A, B))

# using inverse method X = A^-1 * B

x = np.linalg.inv(A).dot(B)
print("uding inverse method = ", x)


[10. 15.]
uding inverse method =  [10. 15.]
